version: "3.9"

services:
  db:
    image: mysql:8.0.0
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=cob1
    ports:
      - "3306:3306"
    volumes:
      - ./db_data:/var/lib/mysql

  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./cobDocs:/cobDocs
    ports:
      - "8000:8000"
    depends_on:
      - db
