# Generated by Django 4.0.1 on 2022-07-19 07:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentTypeMaster',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'document_type_master',
            },
        ),
        migrations.CreateModel(
            name='merchant_data',
            fields=[
                ('merchantId', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, null=True)),
                ('emilId', models.CharField(max_length=255, null=True)),
                ('isEmailVerified', models.SmallIntegerField(null=True)),
                ('isContactNumberVerified', models.SmallIntegerField(null=True)),
                ('contactNumber', models.CharField(max_length=45, null=True)),
                ('contactDesignation', models.CharField(max_length=100, null=True)),
                ('aadharNumber', models.CharField(max_length=45, null=True)),
                ('panCard', models.CharField(max_length=45, null=True)),
                ('accountNumber', models.CharField(max_length=45, null=True)),
                ('bankName', models.CharField(max_length=255, null=True)),
                ('accountHolderName', models.CharField(max_length=255, null=True)),
                ('ifscCode', models.CharField(max_length=45, null=True)),
                ('companyName', models.CharField(max_length=255, null=True)),
                ('companyLogoPath', models.CharField(max_length=255, null=True)),
                ('companyImagePath', models.CharField(max_length=255, null=True)),
                ('companyDescription', models.TextField(null=True)),
                ('companyType', models.CharField(max_length=45, null=True)),
                ('companyWebsite', models.CharField(max_length=255, null=True)),
                ('clientName', models.CharField(max_length=255, null=True)),
                ('clientCode', models.CharField(max_length=45, null=True)),
                ('successUrl', models.CharField(max_length=255, null=True)),
                ('failureUrl', models.CharField(max_length=255, null=True)),
                ('created_date', models.DateTimeField(null=True)),
                ('modified_date', models.DateTimeField(null=True)),
                ('modified_by', models.IntegerField(null=True)),
                ('status', models.CharField(default='Pending', max_length=50, null=True)),
                ('reason', models.CharField(max_length=255, null=True)),
                ('businessType', models.CharField(max_length=45, null=True)),
                ('yourRole', models.CharField(max_length=100, null=True)),
                ('nameOnPanCard', models.CharField(max_length=200, null=True)),
                ('registeredBusinessAdress', models.CharField(max_length=200, null=True)),
                ('stateId', models.CharField(max_length=200, null=True)),
                ('pinCode', models.CharField(max_length=100, null=True)),
                ('registerdWithGST', models.BooleanField(null=True)),
                ('gstNumber', models.CharField(max_length=100, null=True)),
                ('monthlyRevenue', models.CharField(max_length=100, null=True)),
                ('partnerBankId', models.CharField(max_length=100, null=True)),
                ('mouAgreement', models.CharField(max_length=100, null=True)),
                ('constitutionOfMerchant', models.CharField(max_length=200, null=True)),
                ('addressProof', models.CharField(max_length=100, null=True)),
                ('entityProof', models.CharField(max_length=200, null=True)),
                ('utilityBill', models.CharField(max_length=250, null=True)),
                ('panProof', models.CharField(max_length=250, null=True)),
                ('kycOneProof', models.CharField(max_length=150, null=True)),
                ('kycTwoProof', models.CharField(max_length=250, null=True)),
                ('kycThreeProof', models.CharField(max_length=250, null=True)),
                ('kycFourProof', models.CharField(max_length=250, null=True)),
                ('kycFiveProof', models.CharField(max_length=250, null=True)),
                ('bankLetter', models.CharField(max_length=250, null=True)),
                ('onBoardFrom', models.CharField(max_length=200, null=True)),
                ('requestId', models.CharField(max_length=250, null=True)),
                ('clientType', models.CharField(db_column='client_type', max_length=250, null=True)),
                ('parentClientId', models.CharField(db_column='parent_client_id', max_length=250, null=True)),
                ('businessCategory', models.CharField(max_length=250, null=True)),
                ('businessModel', models.CharField(max_length=250, null=True)),
                ('billingLabel', models.CharField(max_length=250, null=True)),
                ('erpCheck', models.CharField(max_length=250, null=True)),
                ('platformId', models.CharField(max_length=250, null=True)),
                ('collectionTypeId', models.CharField(max_length=100, null=True)),
                ('collectionFrequencyId', models.CharField(db_column='collectionFrequencyeId', max_length=100, null=True)),
                ('expectedTransactions', models.CharField(db_column='expectedTransaction', max_length=100, null=True)),
                ('formBuild', models.CharField(max_length=100, null=True)),
                ('ticketSize', models.CharField(max_length=100, null=True)),
                ('signatoryPAN', models.CharField(max_length=250, null=True)),
                ('cityId', models.CharField(max_length=100, null=True)),
                ('operationalAddress', models.CharField(max_length=100, null=True)),
            ],
            options={
                'db_table': 'merchant_data',
            },
        ),
        migrations.CreateModel(
            name='merchant_document',
            fields=[
                ('documentId', models.AutoField(db_column='document_id', primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, null=True)),
                ('filePath', models.CharField(max_length=255, null=True)),
                ('type', models.CharField(max_length=100, null=True)),
                ('isApproved', models.BooleanField(db_column='is_Approved', default=False)),
                ('approvedDate', models.DateTimeField(db_column='approved_date', null=True)),
                ('approvedBy', models.IntegerField(null=True)),
                ('isLatest', models.BooleanField(db_column='is_Latest', null=True)),
                ('createdDate', models.DateTimeField(db_column='created_Date', null=True)),
                ('createdBy', models.IntegerField(db_column='created_By', null=True)),
                ('modifiedDate', models.DateTimeField(db_column='modified_Date', null=True)),
                ('modifiedBy', models.IntegerField(db_column='modified_by', null=True)),
                ('merchantId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='apis.merchant_data')),
            ],
            options={
                'db_table': 'merchant_document',
            },
        ),
    ]
